### ISSUE TITLE
btcd.conf file not automatically created for simnet

### ISSUE THREAD

**Issue by vibhaa** [Roasbeef/btcd#31]
I run `btcd --simnet --txindex --rpcuser=kek --rpcpass=kek` which should create a default btcd.conf, as I understand from the [installation instructions](https://dev.lightning.community/guides/installation/). However, when I run `btcctl --simnet --rpcuser=kek --rpcpass=kek getinfo` after that, I get the following error:

> Error creating a default config file: open /home/ubuntu/.btcd/btcd.conf: no such file or directory
 
the output is: 

> {
  "version": 120000,
  "protocolversion": 70002,
  "blocks": 0,
  "timeoffset": 0,
  "connections": 0,
  "proxy": "",
  "difficulty": 1,
  "testnet": false,
  "relayfee": 0.00001,
  "errors": ""
}

What am I supposed to make out of this? Is this an issue?

**Comment by molxyz** [comment]
@vibhaa Do you still need help with this? All you need to do is go to directory `.btcd` and manually create a btcd.conf.

**Comment by vibhaa** [comment]
Nope, I don't. This has been addressed.
